site_name: BSI-PT Documentation
repo_url: https://github.com/jerry871002/bayesian-strategy-inference

nav:
  - Home: index.md
  - 'Run Individual Experiment': detail.md
  - Experiments:
    - 'Definition': experiments/definition.md
    - 'Experiment 1 Example Figures': experiments/experiment_1_figures.md
    - 'Experiment 2 Example Figures': experiments/experiment_2_figures.md
    - 'Experiment 3 Example Figures': experiments/experiment_3_figures.md
  - Environments:
    - 'Extended batter vs. pitcher game (EBvPG)': environments/baseball_game.md
    - 'Grid World': environments/grid_world.md
    - 'Navigation Game': environments/navigation_game.md
    - 'Soccer Game': environments/soccer_game.md
  - 'Symbols and Terminologies': explain.md
  - 'Developer Guide':
    - 'Getting Started': developer/index.md
    - 'Git Workflow': developer/git_workflow.md
    - 'Pre-commit Hooks': developer/pre_commit_hooks.md
    - 'Documentation Site': developer/documentation_site.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

plugins:
  - glightbox
