[tool.black]
line-length = 100
skip-string-normalization = true

[tool.ruff]
# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default
select = ["E", "F", "W", "I"]
# Disable "Ambiguous variable name"
ignore = ["E741"]

# Allow autofix for isort rules (when `--fix`) is provided.
fixable = ["I"]
unfixable = []

# Same as Black.
line-length = 100

[tool.ruff.per-file-ignores]
# Ignore "Multiple statements on one line" for `get_action`
"**/env.py" = ["E701"]
